#!/bin/bash

echo -n "Enter tag (VM-1):"
read -r TAG
mkdir ../$TAG

echo -n "Instance hostname:"
read -r HOSTNAME

echo -n "Instance user (ubuntu):"
read -r USERNAME
if [[ -z "$USERNAME" ]]
then
	USERNAME="ubuntu"
fi

echo -n "Key name (*):"
read -r KEYNAME
if [[ -z "$KEYNAME" ]]
then
	KEYNAME="*"
fi

echo -n "Instance SSH port (22):"
read -r PORT
if [[ -z "$PORT" ]]
then
	PORT="22"
fi

filecheck="if [[ -d \$1 ]]\nthen\n\trecursive=\"-r \"\nelse\n\trecursive=\"\"\nfi"

printf "$USERNAME\n" > ../$TAG/user.txt
printf "$HOSTNAME\n" > ../$TAG/host.txt
printf "$PORT\n" > ../$TAG/port.txt
printf "#!/bin/bash\nKEYPATH=\"$KEYNAME.pem\"\nUSERNAME=\$(head -n 1 user.txt)\nHOST=\$(head -n 1 host.txt)\nPORT=\$(head -n 1 port.txt)\nssh -p \$PORT -i \$KEYPATH \$USERNAME@\$HOST\n" > ../$TAG/logon && chmod +x ../$TAG/logon
printf "#!/bin/bash\n$filecheck\nKEYPATH=\"$KEYNAME.pem\"\nUSERNAME=\$(head -n 1 user.txt)\nHOST=\$(head -n 1 host.txt)\nPORT=\$(head -n 1 port.txt)\nscp -P \$PORT -i \$KEYPATH \$recursive\$HOME/\$1 \$USERNAME@\$HOST:~/\$2\n" > ../$TAG/copyto && chmod +x ../$TAG/copyto

filecheck="if [[ -d \$2 ]]\nthen\n\trecursive=\"-r \"\nelse\n\trecursive=\"\"\nfi"

printf "#!/bin/bash\n$filecheck\nKEYPATH=\"$KEYNAME.pem\"\nUSERNAME=\$(head -n 1 user.txt)\nHOST=\$(head -n 1 host.txt)\nPORT=\$(head -n 1 port.txt)\nscp -P \$PORT -i \$KEYPATH \$recursive\$USERNAME@\$HOST:~/\$1 \$HOME/\$2\n" > ../$TAG/copyfrom && chmod +x ../$TAG/copyfrom
